### ISSUE TITLE
cluster.schedulingPolicy cannot be SCHED_RR

### ISSUE THREAD

**Issue by bnoordhuis** [ehmicky/portable-node-guide#2]
The README currently says this:

> However on Windows: [..]
> * cluster.schedulingPolicy cannot be SCHED_RR and defaults to SCHED_NONE.

It _can_ be `SCHED_RR` on Windows, it's just really inefficient due to the way Node.js / libuv uses IOCP (long-standing issue.)

You can close this out if you think the current wording serves its purpose but I figured I'd let you know.

**Comment by ehmicky** [comment]
Yes you're right, I just tried it on Windows and it was incorrect indeed. Fixed.
