### ISSUE TITLE
Add section on portable `npm run` scripts

### ISSUE THREAD

**Issue by SteveALee** [ehmicky/portable-node-guide#6]
[Excellent work and comprehensive. I've being doing portable dev for years (actually since DOS)]

A closely related issues is writing npm scripts that are portable. Often  a little care goes a long way but there are limitations and that might causeyou to reach for somehting like [shx](https://github.com/shelljs/shx). Or just use Makefiles :)

I'll dig up an old post it did and link it here.

**Comment by ehmicky** [comment]
Hi @SteveALee, thanks!

What do you precisely put under the words "npm scripts"? I am asking as this could entail several different portability topics:
  - shell like Bash vs Fish vs cmd.exe (covered [here](https://github.com/ehmicky/portable-node-guide#shell))
  - shell execution like `child_process.spawn()` (covered [here](https://github.com/ehmicky/portable-node-guide#files-execution))
  - shell core utilities like `cat` and `sed` (covered [here](https://github.com/ehmicky/portable-node-guide#core-utilities))
  - environment variables (covered [here](https://github.com/ehmicky/portable-node-guide#environment-variables))
  - the specifics of `npm run` itself (I am not aware of any OS-specific issues there)

Your knowledge would be very valuable to this guide, please raise any issues you might find!

**Comment by SteveALee** [comment]
@ehmicky yes `npm run` which closely relates to ENV VARS as the scripts run in a shell and so can set or access them

Basically, the package.json `scripts` section is often used to provide a nice CLI for developers to run commands like `install` and `build` etc. These is bit like good old makefiles but sadly without the minimal build feature. Here's [an example](https://github.com/AlwaysInMind/aim-web-app/blob/master/package.json#L31-L46) from one of my projects.

Here's my 2nd post on it which links to the first. https://opendirective.net/openingaccessibility/2016/03/more-on-portable-npm-scripts/

I'll spend more time when free and maybe PR :)

**Comment by SteveALee** [comment]
> (I am not aware of any OS-specific issues there)

npm run simply passes the script to a shell to be executed - so its easy to write scripts that only run on `sh` +.

**Comment by ehmicky** [comment]
From a quick look at the [source code `npm run`](https://github.com/npm/npm-lifecycle/blob/latest/index.js#L276) it seems like it ultimately does `sh -c ...` on Unix and `cmd.exe /d /s /c ...` with `options.windowsVerbatimArguments: true` on Windows. Comparing with [Node.js source code](https://github.com/nodejs/node/blob/master/lib/child_process.js#L474), this is the same behavior as `child_process.spawn()`'s `options.shell: true`.

I.e. at first glance it seems like `npm run` should not have any more cross-platform issues than `child_process.spawn()` itself (which are covered in the guide).

**Comment by SteveALee** [comment]
AH, it must have changed as it used to look at %COMSPEC% if I recall and that is only set by cmd as far as I recall.

But anyway - yes I agree there arthe same issues however you invoke a subshell - you still need to write portable scripts.

**Comment by ehmicky** [comment]
Yes `%COMSPEC%` seems to be used both by `npm run` and `child_process.spawn()` `options.shell: true`. Too bad they duplicate code there, I think it's legacy because `options.shell` was introduced in Node.js `5.7.0`.

Great article, it was a nice read! However I think the points might already be covered in the following chapters of the guide: [environment variables](https://github.com/ehmicky/portable-node-guide#environment-variables) (including `cross-env`), [Git for Windows / msys / minGW](https://github.com/ehmicky/portable-node-guide#core-utilities) and [local VM](https://github.com/ehmicky/portable-node-guide#testing).

**Comment by SteveALee** [comment]
Thanks 

> However I think the points might already be covered in the following chapters

Perhaps add the portable npm packages like `rimraf` which are easy to use in the context of npm scripts? But you have cros-env :)

**Comment by ehmicky** [comment]
The thing with the npm packages like `rimraf` is that they technically could be achieved with Node.js `fs.*` core utilities. For example instead of `rimraf`, one could use `fs.readdir()` + `fs.unlink()`, and this would be cross-platform as well (i.e. without having to write any `if (process.platform === 'win32')`).

I.e. in my mind those utilities do not fix cross-platform issues, but add convenient wrappers on top of `fs.*` core utilities.

However if you're aware of one those utilities fixing portability problems not addressed by `fs.*` core utilities, please let me know and I'll add them to this guide.

**Comment by SteveALee** [comment]
I see your point but that's why I said 'in the context of npm scripts' where you might just want to use shell scripts and existing commands - not write JS scripts.

It's as "shell scripting" mindset compared to JS scripting.

You can also just use `shx` and I guess you could just add a call to `node -cxxx` but that gets messy with quotes. You could of course also just use JS full stop :)

**Comment by ehmicky** [comment]
I see what you mean now.

While `npm run` scripts are Node.js-specific, they spawn a subshell, so I think the portability of those commands is outside the scope of Node.js itself. For example when `rimraf` is used in the CLI, providing a cross-platform way to remove files, it does not matter anymore which programming language `rimraf` is written in, nor whether it is fired through `npm run` scripts.

I.e. this would be good material for another guide "Portable CLI guide" :)

**Comment by SteveALee** [comment]
heh!

npm is actually a separate package manager and perhaps it could be used without developing for node. It's a general purpose package manager. Not sure if `package.json` is node or npm but they are generally lumped together. Especially as node installs npm as the default package manager.

Many devs choose to use `yarn` so your point is probably true. Even though yarn processes npm scripts in package.json!

But... many front end devs use node as a dev tool only - not the target env.

Life's complicated :)

**Comment by SteveALee** [comment]
heh!

npm is actually a separate package manager and perhaps it could be used without developing for node. It's a general purpose package manager. Not sure if `package.json` is node or npm but they are generally lumped together. Especially as node installs npm as the default package manager.

Many devs choose to use `yarn` so your point is probably true. Even though yarn processes npm scripts in package.json!

But... many front end devs use node as a dev tool only - not the target env.

Life's complicated :)

**Comment by SteveALee** [comment]
Ah, that's the difference

Node as target or node as dev tool platform :) Is see we were coming at it from different angles. THough I use both.
