### ISSUE TITLE
Mention WSL

### ISSUE THREAD

**Issue by SteveALee** [ehmicky/portable-node-guide#7]
WSL is now a very usable option on Windows, though is still slow. However I beelive we should still write for cmd / PS portability.

BTW I use [Git for Windows](https://gitforwindows.org/) bash as my main shell and it works a treat for me. It's based on the old MSYS / MinGW system which I always prefered to Cygwin (actually might use MSYS2) However npm always launches cmd for child shells so you still need portable npm scripts.  :(

**Comment by ehmicky** [comment]
WSL is mentioned [at the end of this section](https://github.com/ehmicky/portable-node-guide#core-utilities).

Git for Windows, MSYS, MinGW and Cygwin are also mentioned there. As I don't use those myself (I directly test on "raw" `cmd.exe`), please let me know if I got their description wrong.

**Comment by SteveALee** [comment]
Ah sorry, I rather scanned read.

It's probably a little unfair to call WSL 'low level'. It's basically a full user land Linux install (CLI only) sitting on Windows OS as the kernel and that does a pretty good job of providing interop with Windows filesystem and running programs.

**Comment by ehmicky** [comment]
Thanks for the feedback on WSL, I've opened a PR #8 to address this. Let me know if it looks good based on your knowledge of WSL!
