### ISSUE TITLE
Proposal of buffer-encoding, cross-sqlcipher

### ISSUE THREAD

**Issue by fritx** [ehmicky/portable-node-guide#9]
Awesome work!

Here's some of my proposal

- For encoding converting: https://www.npmjs.com/package/buffer-encoding
- For encryption on sqlite: https://www.npmjs.com/package/cross-sqlcipher

**Comment by ehmicky** [comment]
Hi @fritx,

Your project is very useful. However I would prefer to recommend `iconv`, `iconv-lite` and `jschardet` as they are the underlying projects used by your project.

On the other hand I've just added a section about [character encoding](https://github.com/ehmicky/portable-node-guide#character-encoding), so thanks for the suggestion! Feel free to read through it and let me know if you find any mistakes, as you probably have a very good understanding of this topic.
